public enum ProblemCategory
{
    LearnCC = 0,
    SchoolGFG = 1,
    BeginnerCC = 2,
    SevenKyu = 3,
    EightKyu = 4,
    BasicGFG = 5,
    SixKyu = 6,
    FiveKyu = 7,
    EasyCB = 8,
    EasyGFG = 9,
    EasyHR = 10,
    EasyLC = 11,
    FourKyu = 12,
    ThreeKyu = 13,
    MediumGFG = 14,
    MediumHR = 15,
    MediumLC = 16,
    TwoKyu = 17,
    OneKyu = 18,
    HardGFG = 19,
    HardHR = 20,
    HardLC = 21,
}