namespace CompetitiveProgramming;
public enum ProblemCategory
{
    Unknown = 0,

    LearnCC = 1,
    SchoolGFG = 2,
    BeginnerCC = 3,
    BeginnerAC = 4,
    SevenKyu = 5,
    EightKyu = 6,
    BasicGFG = 7,
    SixKyu = 8,
    FiveKyu = 9,
    EasyCB = 10,
    EasyGFG = 11,
    EasyHR = 12,
    EasyLC = 13,
    FourKyu = 14,
    ThreeKyu = 15,
    MediumGFG = 16,
    MediumHR = 17,
    MediumLC = 18,
    TwoKyu = 19,
    OneKyu = 20,
    HardGFG = 21,
    HardHR = 22,
    HardLC = 23,
    CF800 = 24,
}